#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateSample
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    public partial class HelperTestTemplate : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
#line hidden
public System.Web.WebPages.HelperResult FormatFoo(string foo) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 2 "..\..\HelperTestTemplate.cshtml"
                               
	
#line default
#line hidden


#line 3 "..\..\HelperTestTemplate.cshtml"
WriteTo(@__razor_helper_writer, foo.ToUpper());

#line default
#line hidden


#line 3 "..\..\HelperTestTemplate.cshtml"
               

#line default
#line hidden

});

}


        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");


            
            #line 6 "..\..\HelperTestTemplate.cshtml"
  
    var foos = new[] {
        "foo one",
        "foo two",
        "foo three"
    };


            
            #line default
            #line hidden
WriteLiteral("\r\n** HelperTestTemplate **\r\n\r\nFoos:\r\n<ul>\r\n");


            
            #line 18 "..\..\HelperTestTemplate.cshtml"
     foreach (var foo in foos)
    {

            
            #line default
            #line hidden
WriteLiteral("        <li>");


            
            #line 20 "..\..\HelperTestTemplate.cshtml"
       Write(foo);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");


            
            #line 21 "..\..\HelperTestTemplate.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n\r\nFormatted foos:\r\n<ul>\r\n");


            
            #line 26 "..\..\HelperTestTemplate.cshtml"
     foreach (var foo in foos)
    {

            
            #line default
            #line hidden
WriteLiteral("        <li>");


            
            #line 28 "..\..\HelperTestTemplate.cshtml"
       Write(FormatFoo(foo));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n");


            
            #line 29 "..\..\HelperTestTemplate.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n");


        }
    }
}
#pragma warning restore 1591
