#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateSample
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    public partial class ItemTemplate : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 2 "..\..\ItemTemplate.cshtml"

    public string Foo { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n<li>");


            
            #line 5 "..\..\ItemTemplate.cshtml"
Write(Foo);

            
            #line default
            #line hidden
WriteLiteral("</li>");


        }
    }
}
#pragma warning restore 1591
