#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateSample
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\ListTemplate.cshtml"
    using TemplateSample;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.0.0")]
    public partial class ListTemplate : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 3 "..\..\ListTemplate.cshtml"

    public IEnumerable<string> Foos { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



WriteLiteral("\r\n");


            
            #line 6 "..\..\ListTemplate.cshtml"
  
    var itemTemplate = new ItemTemplate();


            
            #line default
            #line hidden
WriteLiteral("\r\n<ul>\r\n");


            
            #line 11 "..\..\ListTemplate.cshtml"
     foreach (var foo in Foos)
    {
        itemTemplate.Foo = foo; 
        itemTemplate.Clear();
        
            
            #line default
            #line hidden
            
            #line 15 "..\..\ListTemplate.cshtml"
   Write(itemTemplate.TransformText());

            
            #line default
            #line hidden
            
            #line 15 "..\..\ListTemplate.cshtml"
                                     
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>");


        }
    }
}
#pragma warning restore 1591
