#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateSample
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    public partial class MailTemplate : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


            WriteLiteral("\r\n\r\nSome mail\r\n");


        }
    }
}
#pragma warning restore 1591
