#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrecompiledMvcLibrary.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Html;
    
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorSingleFileGenerator", "0.7.0.0")]
    public class _Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
#line hidden

        public _Layout()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {


WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>");


      Write(ViewBag.Title);

WriteLiteral("</title>\r\n    <link href=\"");


           Write(Url.Content("~/Content/Site.css"));

WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\" />\r\n    <script src=\"");


            Write(Url.Content("~/Scripts/jquery-1.4.4.min.js"));

WriteLiteral(@""" type=""text/javascript""></script>
</head>

<body>
    <div class=""page"">

        <div id=""header"">
            <div id=""title"">
                <h1>My MVC Application</h1>
            </div>

            <div id=""logindisplay"">
                ");


           Write(Html.Partial("_LogOnPartial"));

WriteLiteral("\r\n            </div>\r\n\r\n            <div id=\"menucontainer\">\r\n\r\n                <" +
"ul id=\"menu\">\r\n                    <li>");


                   Write(Html.ActionLink("Home", "Index", "Home"));

WriteLiteral("</li>\r\n                    <li>");


                   Write(Html.ActionLink("About", "About", "Home"));

WriteLiteral("</li>\r\n                </ul>\r\n\r\n            </div>\r\n        </div>\r\n\r\n        <di" +
"v id=\"main\">\r\n            ");


       Write(RenderBody());

WriteLiteral("\r\n            <div id=\"footer\">\r\n            </div>\r\n        </div>\r\n    </div>\r\n" +
"</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
