#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrecompiledMvcLibrary.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Html;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "D:\Code\Codeplex\RazorGenerator\samples\PrecompiledMvcLibrary\Views\Home\ExternalPrecompiled.cshtml"
    using PrecompiledMvcLibrary.Views.Shared;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/ExternalPrecompiled.cshtml")]
    public class ExternalPrecompiled : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ExternalPrecompiled()
        {
        }
        public override void Execute()
        {

WriteLiteral("\r\n");


            
            #line 3 "D:\Code\Codeplex\RazorGenerator\samples\PrecompiledMvcLibrary\Views\Home\ExternalPrecompiled.cshtml"
  
    ViewBag.Title = "Home Page";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>");


            
            #line 7 "D:\Code\Codeplex\RazorGenerator\samples\PrecompiledMvcLibrary\Views\Home\ExternalPrecompiled.cshtml"
Write(ViewBag.Message);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n<p>\r\n    To learn more about ASP.NET MVC visit <a href=\"http://asp.net/mvc" +
"\" title=\"ASP.NET MVC Website\">http://asp.net/mvc</a>.\r\n</p>\r\n\r\n<h2>\r\n    I\'m in " +
"an assembly!\r\n</h2>\r\n\r\n");


            
            #line 16 "D:\Code\Codeplex\RazorGenerator\samples\PrecompiledMvcLibrary\Views\Home\ExternalPrecompiled.cshtml"
Write(Html.ObjectInfo(this));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 18 "D:\Code\Codeplex\RazorGenerator\samples\PrecompiledMvcLibrary\Views\Home\ExternalPrecompiled.cshtml"
Write(Html.Partial("~/Views/Shared/_ViewTypes.cshtml"));

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
