#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrecompiledMvcLibrary.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/MockHttpContext.cshtml")]
    public partial class MockHttpContext : System.Web.Mvc.WebViewPage<dynamic>
    {
        public MockHttpContext()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Home\MockHttpContext.cshtml"
  
    Layout = null;


            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n<head>\r\n    <meta name=\"viewport\" content=\"width=dev" +
"ice-width\" />\r\n    <title></title>\r\n</head>\r\n<body>\r\n    <div>\r\n");


            
            #line 14 "..\..\Views\Home\MockHttpContext.cshtml"
         if (Context.Request.IsAuthenticated)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div id=\"user-authenticated\"></div>\r\n");


            
            #line 17 "..\..\Views\Home\MockHttpContext.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
