#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrecompiledMvcLibrary.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Html;
    
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/LogOn.cshtml")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorSingleFileGenerator", "0.6.0.0")]
    public class _Page_Views_Account_LogOn_cshtml : System.Web.Mvc.WebViewPage<PrecompiledMvcSample.Models.LogOnModel>
    {
#line hidden

        public _Page_Views_Account_LogOn_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n");


  
    ViewBag.Title = "Log On";


WriteLiteral("\r\n<h2>Log On</h2>\r\n<p>\r\n    Please enter your username and password. ");


                                        Write(Html.ActionLink("Register", "Register"));

WriteLiteral(" if you don\'t have an account.\r\n</p>\r\n\r\n<script src=\"");


        Write(Url.Content("~/Scripts/jquery.validate.min.js"));

WriteLiteral("\" type=\"text/javascript\"></script>\r\n<script src=\"");


        Write(Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js"));

WriteLiteral("\" type=\"text/javascript\"></script>\r\n\r\n");


Write(Html.ValidationSummary(true, "Login was unsuccessful. Please correct the errors and try again."));

WriteLiteral("\r\n\r\n");


 using (Html.BeginForm()) {

WriteLiteral("    <div>\r\n        <fieldset>\r\n            <legend>Account Information</legend>\r\n" +
"\r\n            <div class=\"editor-label\">\r\n                ");


           Write(Html.LabelFor(m => m.UserName));

WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");


           Write(Html.TextBoxFor(m => m.UserName));

WriteLiteral("\r\n                ");


           Write(Html.ValidationMessageFor(m => m.UserName));

WriteLiteral("\r\n            </div>\r\n\r\n            <div class=\"editor-label\">\r\n                ");


           Write(Html.LabelFor(m => m.Password));

WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");


           Write(Html.PasswordFor(m => m.Password));

WriteLiteral("\r\n                ");


           Write(Html.ValidationMessageFor(m => m.Password));

WriteLiteral("\r\n            </div>\r\n\r\n            <div class=\"editor-label\">\r\n                ");


           Write(Html.CheckBoxFor(m => m.RememberMe));

WriteLiteral("\r\n                ");


           Write(Html.LabelFor(m => m.RememberMe));

WriteLiteral("\r\n            </div>\r\n\r\n            <p>\r\n                <input type=\"submit\" val" +
"ue=\"Log On\" />\r\n            </p>\r\n        </fieldset>\r\n    </div>\r\n");


}


        }
    }
}
#pragma warning restore 1591
