#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrecompiledMvcLibrary.Areas.MyPluggableArea.Views.Foo
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/MyPluggableArea/Views/Foo/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {


#line 1 "..\..\Areas\MyPluggableArea\Views\Foo\Index.cshtml"

            Layout = null;



#line default
#line hidden
            WriteLiteral("\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n<head>\r\n    <title>Index</title>\r\n</head>\r\n<body>\r\n " +
            "   <div>\r\n        <h1>Foo\\Index view from MyPluggableArea!</h1>\r\n    </div>\r\n</b" +
            "ody>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
