#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcApplicationTestRazorGenerator.Views.Helpers;
    using SampleRazorHelperLibrary;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public static class _Views_Helpers_WebAppHelpers_cshtml
    {

public static System.Web.WebPages.HelperResult WriteList(string[] items) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 3 "..\..\Views\Helpers\WebAppHelpers.cshtml"
                                   

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    <ul>\r\n");



#line 5 "..\..\Views\Helpers\WebAppHelpers.cshtml"
         foreach (var s in items) {

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "            <li>\r\n                ");



#line 7 "..\..\Views\Helpers\WebAppHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, s);

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "!  (from webapp)\r\n            </li>\r\n");



#line 9 "..\..\Views\Helpers\WebAppHelpers.cshtml"
        }

#line default
#line hidden

WebViewPage.WriteLiteralTo(@__razor_helper_writer, "    </ul>\r\n");



#line 11 "..\..\Views\Helpers\WebAppHelpers.cshtml"

#line default
#line hidden

});

}


public static System.Web.WebPages.HelperResult RenderAboutLink(System.Web.Mvc.HtmlHelper Html) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 14 "..\..\Views\Helpers\WebAppHelpers.cshtml"
                                                         
    
#line default
#line hidden


#line 15 "..\..\Views\Helpers\WebAppHelpers.cshtml"
WebViewPage.WriteTo(@__razor_helper_writer, Html.ActionLink("About link from helper", "About", "Home"));

#line default
#line hidden


#line 15 "..\..\Views\Helpers\WebAppHelpers.cshtml"
                                                               ;

#line default
#line hidden

});

}


    }
}
#pragma warning restore 1591
