// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RazorGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "2FD58EB3-29A2-40A3-BE17-C024CA9A17A2";
        public const string Name = "Razor Generator";
        public const string Description = @"Generates *.cs and *.vb source code from Razor files (*.cshtml and *.vbhtml respectively) directly from within Visual Studio at design-time without requiring a build. This extension supports Razor files used natively by ASP.NET MVC, ASP.NET Web Pages and standalone templates. This extension is not necessary to compile  *.cshtml and .*vbhtml files at build-time using MSBuild.";
        public const string Language = "en-US";
        public const string Version = "2.0.0";
        public const string Author = "RazorGenerator contributors";
        public const string Tags = "razor cshtml vbhtml precompile precompiler";
    }
}
