#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrecompiledMvcLibrary.Views.Account
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ChangePasswordSuccess.cshtml")]
    public class ChangePasswordSuccess : System.Web.Mvc.WebViewPage<dynamic>
    {
        public ChangePasswordSuccess()
        {
        }
        public override void Execute()
        {


#line 1 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePasswordSuccess.cshtml"

            ViewBag.Title = "Change Password";



#line default
#line hidden
            WriteLiteral("\r\n<h2>Change Password</h2>\r\n<p>\r\n    Your password has been changed successfully." +
            "\r\n</p>\r\n");


        }
    }
}
#pragma warning restore 1591
