#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrecompiledMvcLibrary.Views.Account
{
    using System.Web.Mvc.Html;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ChangePassword.cshtml")]
    public class ChangePassword : System.Web.Mvc.WebViewPage<MvcSample.Models.ChangePasswordModel>
    {
        public ChangePassword()
        {
        }
        public override void Execute()
        {

            WriteLiteral("\r\n");



#line 3 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"

            ViewBag.Title = "Change Password";



#line default
#line hidden
            WriteLiteral("\r\n<h2>Change Password</h2>\r\n<p>\r\n    Use the form below to change your password. " +
            "\r\n</p>\r\n<p>\r\n    New passwords are required to be a minimum of ");



#line 12 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"
            Write(ViewBag.PasswordLength);


#line default
#line hidden
            WriteLiteral(" characters in length.\r\n</p>\r\n\r\n<script src=\"");



#line 15 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"
            Write(Url.Content("~/Scripts/jquery.validate.min.js"));


#line default
#line hidden
            WriteLiteral("\" type=\"text/javascript\"></script>\r\n<script src=\"");



#line 16 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"
            Write(Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js"));


#line default
#line hidden
            WriteLiteral("\" type=\"text/javascript\"></script>\r\n\r\n");



#line 18 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"
            using (Html.BeginForm())
            {


#line default
#line hidden

#line 19 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"
                Write(Html.ValidationSummary(true, "Password change was unsuccessful. Please correct the errors and try again."));


#line default
#line hidden

#line 19 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"



#line default
#line hidden
                WriteLiteral("    <div>\r\n        <fieldset>\r\n            <legend>Account Information</legend>\r\n" +
                "\r\n            <div class=\"editor-label\">\r\n                ");



#line 25 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"
                Write(Html.LabelFor(m => m.OldPassword));


#line default
#line hidden
                WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");



#line 28 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"
                Write(Html.PasswordFor(m => m.OldPassword));


#line default
#line hidden
                WriteLiteral("\r\n                ");



#line 29 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"
                Write(Html.ValidationMessageFor(m => m.OldPassword));


#line default
#line hidden
                WriteLiteral("\r\n            </div>\r\n\r\n            <div class=\"editor-label\">\r\n                ");



#line 33 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"
                Write(Html.LabelFor(m => m.NewPassword));


#line default
#line hidden
                WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");



#line 36 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"
                Write(Html.PasswordFor(m => m.NewPassword));


#line default
#line hidden
                WriteLiteral("\r\n                ");



#line 37 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"
                Write(Html.ValidationMessageFor(m => m.NewPassword));


#line default
#line hidden
                WriteLiteral("\r\n            </div>\r\n\r\n            <div class=\"editor-label\">\r\n                ");



#line 41 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"
                Write(Html.LabelFor(m => m.ConfirmPassword));


#line default
#line hidden
                WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");



#line 44 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"
                Write(Html.PasswordFor(m => m.ConfirmPassword));


#line default
#line hidden
                WriteLiteral("\r\n                ");



#line 45 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"
                Write(Html.ValidationMessageFor(m => m.ConfirmPassword));


#line default
#line hidden
                WriteLiteral("\r\n            </div>\r\n\r\n            <p>\r\n                <input type=\"submit\" val" +
                "ue=\"Change Password\" />\r\n            </p>\r\n        </fieldset>\r\n    </div>\r\n");



#line 53 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\ChangePassword.cshtml"
            }


#line default
#line hidden

        }
    }
}
#pragma warning restore 1591
