#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrecompiledMvcLibrary.Views.Account
{
    using System.Web.Mvc.Html;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Register.cshtml")]
    public class Register : System.Web.Mvc.WebViewPage<MvcSample.Models.RegisterModel>
    {
        public Register()
        {
        }
        public override void Execute()
        {


            WriteLiteral("\r\n\r\n");


            WriteLiteral("\r\n");



#line 5 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"

            ViewBag.Title = "Register";



#line default
#line hidden
            WriteLiteral("\r\n<h2>Create a New Account</h2>\r\n<p>\r\n    Use the form below to create a new acco" +
            "unt. \r\n</p>\r\n<p>\r\n    Passwords are required to be a minimum of ");



#line 14 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
            Write(ViewBag.PasswordLength);


#line default
#line hidden
            WriteLiteral(" characters in length.\r\n</p>\r\n\r\n<script src=\"");



#line 17 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
            Write(Url.Content("~/Scripts/jquery.validate.min.js"));


#line default
#line hidden
            WriteLiteral("\" type=\"text/javascript\"></script>\r\n<script src=\"");



#line 18 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
            Write(Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js"));


#line default
#line hidden
            WriteLiteral("\" type=\"text/javascript\"></script>\r\n\r\n");



#line 20 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
            using (Html.BeginForm())
            {


#line default
#line hidden

#line 21 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
                Write(Html.ValidationSummary(true, "Account creation was unsuccessful. Please correct the errors and try again."));


#line default
#line hidden

#line 21 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"



#line default
#line hidden
                WriteLiteral("    <div>\r\n        <fieldset>\r\n            <legend>Account Information</legend>\r\n" +
                "\r\n            <div class=\"editor-label\">\r\n                ");



#line 27 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
                Write(Html.LabelFor(m => m.UserName));


#line default
#line hidden
                WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");



#line 30 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
                Write(Html.TextBoxFor(m => m.UserName));


#line default
#line hidden
                WriteLiteral("\r\n                ");



#line 31 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
                Write(Html.ValidationMessageFor(m => m.UserName));


#line default
#line hidden
                WriteLiteral("\r\n            </div>\r\n\r\n            <div class=\"editor-label\">\r\n                ");



#line 35 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
                Write(Html.LabelFor(m => m.Email));


#line default
#line hidden
                WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");



#line 38 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
                Write(Html.TextBoxFor(m => m.Email));


#line default
#line hidden
                WriteLiteral("\r\n                ");



#line 39 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
                Write(Html.ValidationMessageFor(m => m.Email));


#line default
#line hidden
                WriteLiteral("\r\n            </div>\r\n\r\n            <div class=\"editor-label\">\r\n                ");



#line 43 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
                Write(Html.LabelFor(m => m.Password));


#line default
#line hidden
                WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");



#line 46 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
                Write(Html.PasswordFor(m => m.Password));


#line default
#line hidden
                WriteLiteral("\r\n                ");



#line 47 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
                Write(Html.ValidationMessageFor(m => m.Password));


#line default
#line hidden
                WriteLiteral("\r\n            </div>\r\n\r\n            <div class=\"editor-label\">\r\n                ");



#line 51 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
                Write(Html.LabelFor(m => m.ConfirmPassword));


#line default
#line hidden
                WriteLiteral("\r\n            </div>\r\n            <div class=\"editor-field\">\r\n                ");



#line 54 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
                Write(Html.PasswordFor(m => m.ConfirmPassword));


#line default
#line hidden
                WriteLiteral("\r\n                ");



#line 55 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
                Write(Html.ValidationMessageFor(m => m.ConfirmPassword));


#line default
#line hidden
                WriteLiteral("\r\n            </div>\r\n\r\n            <p>\r\n                <input type=\"submit\" val" +
                "ue=\"Register\" />\r\n            </p>\r\n        </fieldset>\r\n    </div>\r\n");



#line 63 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Account\Register.cshtml"
            }


#line default
#line hidden

        }
    }
}
#pragma warning restore 1591
