#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleRazorHelperLibrary
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    using System.Web.UI;
    using WebMatrix.Data;
    using WebMatrix.WebData;
    
    // Last Generated Timestamp: 04/21/2011 11:32 AM
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorSingleFileGenerator", "1.0.0.0")]
    public class BasicSample : SampleRazorHelperLibrary.BasicSampleTemplateBaseClass
    {
#line hidden

        public BasicSample()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("<div>\r\n    This is a simple template that derives from a custom base class\r\n</div" +
">");


        }
    }
}
#pragma warning restore 1591
