#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleRazorHelperLibrary
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Security;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorSingleFileGenerator", "0.6.0.0")]
    public class CustomHostSample : System.Web.WebPages.WebPage
    {
#line hidden

        public CustomHostSample()
        {
        }
        private string CustomProperty
        {
            get
            {
                return "Hello world";
            }
        }
        public override void Execute()
        {


WriteLiteral("\r\n\r\nThe output file should have a property called \"CustomProperty\"");


        }
    }
}
#pragma warning restore 1591
