//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleRazorHelperLibrary
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorSingleFileGenerator", "1.0")]
    public class LibraryHelpers : System.Web.WebPages.HelperPage
    {
#line hidden
#line hidden
public static System.Web.WebPages.HelperResult WriteList(string[] items) {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {


                                   

WriteLiteralTo(@__razor_helper_writer, "    <ul>\r\n");


         foreach (var s in items) {

WriteLiteralTo(@__razor_helper_writer, "            <li>\r\n                ");


WriteTo(@__razor_helper_writer, s);

WriteLiteralTo(@__razor_helper_writer, "! (from library)\r\n            </li>\r\n");


        }

WriteLiteralTo(@__razor_helper_writer, "    </ul>\r\n");



});

}


        public LibraryHelpers()
        {
        }
        protected static System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
    }
}
