#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    public class WebPagesHelperSample : System.Web.WebPages.HelperPage
    {
#line hidden
#line hidden
        public static System.Web.WebPages.HelperResult PrintTime()
        {
            return new System.Web.WebPages.HelperResult(__razor_helper_writer =>
            {



#line 1 "D:\forks\razorsinglefilegenerator\samples\PrecompiledWebPagesLibrary\WebPagesHelperSample.cshtml"


#line default
#line hidden

                WriteLiteralTo(@__razor_helper_writer, "    <span class=\"time\">The time is now ");



#line 2 "D:\forks\razorsinglefilegenerator\samples\PrecompiledWebPagesLibrary\WebPagesHelperSample.cshtml"
                WriteTo(@__razor_helper_writer, DateTime.Now.TimeOfDay);

#line default
#line hidden

                WriteLiteralTo(@__razor_helper_writer, "</span>\r\n");



#line 3 "D:\forks\razorsinglefilegenerator\samples\PrecompiledWebPagesLibrary\WebPagesHelperSample.cshtml"

#line default
#line hidden

            });

        }


        public WebPagesHelperSample()
        {
        }
    }
}
#pragma warning restore 1591
