#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrecompiledMvcSample.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using PrecompiledMvcLibrary.Views.Shared;
    using System.Web.Mvc;
    using System.Web.Mvc.Html;
    
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/InAppPrecompiled.cshtml")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorSingleFileGenerator", "0.6.0.0")]
    public class _Page_Views_Home_InAppPrecompiled_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
#line hidden

        public _Page_Views_Home_InAppPrecompiled_cshtml()
        {
        }
        protected System.Web.HttpApplication ApplicationInstance
        {
            get
            {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n<h3>This is executing as a precompiled view.</h3>\r\n\r\n");


 using (Html.BeginForm()) {
    

WriteLiteral("    <label>");


      Write(Html.CheckBox("executePrecompiledEngineFirst"));

WriteLiteral(" <strong>Precompiled view engine executes first</strong>&nbsp;</label>\r\n");




WriteLiteral("    <input type=\"submit\" value=\"Submit\" />\r\n");


    
}

WriteLiteral("\r\n");


Write(Html.ObjectInfo(this));

WriteLiteral("\r\n\r\n");


Write(RenderPage("~/Views/Shared/_ViewTypes.cshtml"));


        }
    }
}
#pragma warning restore 1591
