#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrecompiledMvcLibrary.Views.Shared
{
    using System.Web.Mvc.Html;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public class _Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Layout()
        {
        }
        public override void Execute()
        {
            WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>");



#line 4 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Shared\_Layout.cshtml"
            Write(ViewBag.Title);


#line default
#line hidden
            WriteLiteral("</title>\r\n    <link href=\"");



#line 5 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Shared\_Layout.cshtml"
            Write(Url.Content("~/Content/Site.css"));


#line default
#line hidden
            WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\" />\r\n    <script src=\"");



#line 6 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Shared\_Layout.cshtml"
            Write(Url.Content("~/Scripts/jquery-1.4.4.min.js"));


#line default
#line hidden
            WriteLiteral(@""" type=""text/javascript""></script>
</head>

<body>
    <div class=""page"">

        <div id=""header"">
            <div id=""title"">
                <h1>My MVC Application</h1>
            </div>

            <div id=""logindisplay"">
                ");



#line 18 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Shared\_Layout.cshtml"
            Write(Html.Partial("_LogOnPartial"));


#line default
#line hidden
            WriteLiteral("\r\n            </div>\r\n\r\n            <div id=\"menucontainer\">\r\n\r\n                <" +
            "ul id=\"menu\">\r\n                    <li>");



#line 24 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Shared\_Layout.cshtml"
            Write(Html.ActionLink("Home", "Index", "Home"));


#line default
#line hidden
            WriteLiteral("</li>\r\n                    <li>");



#line 25 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Shared\_Layout.cshtml"
            Write(Html.ActionLink("About", "About", "Home"));


#line default
#line hidden
            WriteLiteral("</li>\r\n                </ul>\r\n\r\n            </div>\r\n        </div>\r\n\r\n        <di" +
            "v id=\"main\">\r\n            ");



#line 32 "D:\forks\razorsinglefilegenerator\samples\PrecompiledMvcLibrary\Views\Shared\_Layout.cshtml"
            Write(RenderBody());


#line default
#line hidden
            WriteLiteral("\r\n            <div id=\"footer\">\r\n            </div>\r\n        </div>\r\n    </div>\r\n" +
            "</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
